//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMOWebsite.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedbackQuestionAnswer
    {
        public int FeedbackQuestionAnswerID { get; set; }
        public int ProjectFeedbackID { get; set; }
        public int FeedbackQuestionID { get; set; }
        public Nullable<int> FeedbackAnswerRank { get; set; }
        public string FeedbackAnswerOpenEnd { get; set; }
    
        public virtual tblFeedbackQuestion tblFeedbackQuestion { get; set; }
        public virtual tblProjectFeedback tblProjectFeedback { get; set; }
    }
}
