//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMOWebsite.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectStatusUpdate
    {
        public int ProjectStatusUpdatesID { get; set; }
        public int ProjectID { get; set; }
        public string ProjectStatusUpdate { get; set; }
        public System.DateTime ProjectStatusUpdateDate { get; set; }
    
        public virtual tblProjectInformation tblProjectInformation { get; set; }
    }
}
