//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMOWebsite.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectFeedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProjectFeedback()
        {
            this.tblFeedbackQuestionAnswers = new HashSet<tblFeedbackQuestionAnswer>();
        }
    
        public int ProjectFeedbackID { get; set; }
        public int ProjectID { get; set; }
        public string FeedbackSubmitterName { get; set; }
        public string FeedbackSubmitterEmail { get; set; }
        public string FeedbackSubmitterDepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFeedbackQuestionAnswer> tblFeedbackQuestionAnswers { get; set; }
        public virtual tblProjectInformation tblProjectInformation { get; set; }
    }
}
